name: MinersVillagesPlugin
version: '${project.version}'
main: com.conquerski.minersvillages.MinersVillagesPlugin
api-version: 1.19
authors: [ ConquerSki ]
description: A repair tools plugin used for Miner's Village server!
softdepend: [Vault,CoreProtect]
commands:
  xl:
    description: 你可以付一定的钱来修理你当前手里拿着的装备
  xlgui:
    description: 修理GUI界面